# Generated by Django 3.2.9 on 2021-12-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librogramapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='created_on',
        ),
    ]
