# Generated by Django 3.2.9 on 2021-12-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librogramapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
