# Generated by Django 3.2.9 on 2021-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librogramapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggoal',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='readinggoal',
            name='number_of_books',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='readinggoal',
            name='number_of_pages',
            field=models.IntegerField(null=True),
        ),
    ]
