# Generated by Django 4.0 on 2021-12-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librogramapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
